aanpassen readme, index en releasenotes voor specifiek RvIG versie
VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG pull request #5
Opened 2021-01-13 11:51 UTC by fsamwel

2021-01-28 10:27 UTC, melsk-r commented on README.md
Deze bullet over de API-Key wordt in de RvIG versie weggelaten. Ik neem toch aan dat er straks ook bij RvIG een API-Key aangevraagd moet worden. Ik kan me voorstellen dat dat nu nog niet kan maar moeten we dan hier niet iets zetten als 'Zodra deze API door het RvIG zal worden aangeboden zullen we voorzien in een link naar waar een API-Key aangevraagd kan worden.'

2021-01-28 10:34 UTC, melsk-r commented on docs/index.md
>  * Lees de [Getting started](./getting-started)
'(./getting-started)' kan volgens mij vervangen worden door simpelweg '(getting-started)'.

2021-01-28 10:37 UTC, melsk-r requested changes
Zie geplaatste comments.

2021-02-08 10:54 UTC, CathyDingemanse approved these changes

2021-02-08 15:00 UTC, fsamwel commented on README.md
heb deze weer toegevoegd

2021-02-19 12:09 UTC, merged